import 'package:firebase_core/firebase_core.dart';

/// Firebase configuration for Shivam Cyber Cafe.
///
/// IMPORTANT: Replace the placeholder values with the values generated by
/// `flutterfire configure` for your Firebase project. The app remains fully
/// offline when these values are empty.
class CloudConfig {
  static const enabled = false;

  static const apiKey = '';
  static const appId = '';
  static const messagingSenderId = '';
  static const projectId = '';
  static const storageBucket = '';

  static bool get isConfigured =>
      enabled &&
      apiKey.isNotEmpty &&
      appId.isNotEmpty &&
      messagingSenderId.isNotEmpty &&
      projectId.isNotEmpty;

  static FirebaseOptions get options => const FirebaseOptions(
        apiKey: apiKey,
        appId: appId,
        messagingSenderId: messagingSenderId,
        projectId: projectId,
        storageBucket: storageBucket,
      );
}
